### ISSUE TITLE
A float value loses precision

### ISSUE THREAD

**Issue by nikoudel** [eriktim/protoc-gen-elm#4]
I'm [trying out](https://github.com/nikoudel/elm-protobuf-poc) the library and I've noticed one thing looking suspicious.

When passing a [float](https://github.com/nikoudel/elm-protobuf-poc/blob/master/protobuf/Messages.proto) value e.g. 5000.195 from client to server, it gets deserialized properly on the server side but then becomes 5000.19482421875 after having travelled back to the client (serialized/deserialized once again). It would not be confusing if the value looked something like 5000.194999999991 but the difference is around 0.0002 which is quite large.

Is there some reasonable explanation to that behavior? There is a [demo app](http://elm-cars.hi5.run/) running the code mentioned above.

**Comment by eriktim** [comment]
As mentioned [here](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/latest/Protobuf-Encode#float), float values may loose some precision. This is because they are represented using 32 bits. Doubles use 64 bits. Therefore a double value cannot always be exactly represented using a float. `5000.19482421875` is the closest you can get to `5000.195` using a float. See e.g. [wikipedia](https://en.wikipedia.org/wiki/Single-precision_floating-point_format) for some more background on this.
